### ISSUE TITLE
Multiple audiences

### ISSUE THREAD

**Issue by absowoot** [pow-auth/assent#111]
Hello! I'm pretty new to Elixir so forgive me if this has an easy answer. I'm creating a custom OIDC provider (Netsuite) that issues 2 audiences in a list, one of which is the client ID.

In the oidc.ex, audience validation simply matches what's returned in the claim with the client_id but unfortunately this always produces the "Invalid audience" error. 

How would I go about filtering the data so that I could either remove the other audience or add it to what's being matched? I'm trying to follow along with the Apple OIDC provider but can't quite make sense of it.

**Comment by danschultzer** [comment]
Unfortunately, no support for this in Assent, but it definitely should be supported. I'm reading through [the specs](https://openid.net/specs/openid-connect-core-1_0.html) to understand well how it should be handled and will push a PR to fix it. Thanks for your patience!

**Comment by danschultzer** [comment]
You can try out #113. I believe it follows correctly the rules in https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation, point 3, 4, and 5. I'll review later to make sure I got it right. You'll have to configure the list trusted audiences as the specs requires.

Reading the [netsuite docs](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_161235023782.html) I'm confused what it's meant with comma separated list. From the specs it sounds like it should just be a list, not a comma separated string. Let me know if it works for you.

**Comment by absowoot** [comment]
Thank you for the update! I have tried #113 but now I am receiving an error about a missing azp -- it appears that Netsuite does not provide that.

When I remove [references to azp](https://github.com/pow-auth/assent/pull/113/files#diff-509346f68552737001c92184e600fa1338ebcd4a4e511d6683057810f313cb83R344) (lines 344, 346, 350) I am able to successfully log in.

As for the comma-separated list of audiences, your implementation works as expected. For reference, here is what Netsuite returns:

```
[
	{"at_hash", "..."},
 	{"aud", ["########-####-####-####-############;CLIENT_ID", "AUDIENCE"]},
	{"email", "..."},
	{"email_verified", false},
	{"exp", 1677088887},
	{"iat", 1677078087},
	{"iss", "https://system.netsuite.com"},
	{"jti", "CLIENT_ID.i-a.########-####-####-####-############_#############.#"},
	{"nonce", "05mTnGHTHzksKoiGF7DK1w"}, 
	{"scope", ["email", "openid"]}, 
	{"sub", "3;73799"}
]
```

**Comment by danschultzer** [comment]
Thanks! Didn't read it carefully yesterday, but `azp` is just a recommendation. It's only required to validate if it exists in the token. I've updated the PR, and will get it merged and released once I fix an upstream issue I'm experiencing with the CI.

**Comment by absowoot** [comment]
The update works perfectly, thanks!

**Comment by ejmartin504** [comment]
I know this is quite old, but I'm trying to validate a google OAuth token from an android app and running into an issue with aud vs. azp

The thing is the aud and azp values do not match. The aud value is the client_id, but the azp value is the client_id of the android app

This should be allowed, per the spec


> OPTIONAL. Authorized party - the party to which the ID Token was issued. If present, it MUST contain the OAuth 2.0 Client ID of this party. The azp value is a case-sensitive string containing a StringOrURI value. Note that in practice, the azp Claim only occurs when extensions beyond the scope of this specification are used; therefore, implementations not using such extensions are encouraged to not use azp and to ignore it when it does occur.

I had to read this a few times to understand, but the key part is "If present, it MUST contain the OAuth 2.0 Client ID of this party." -- by "this" party it does not mean the client_id currently being used to authenticate, but the client_id of the _authorized party_ itself. So right now, I can't validate my token because aud == client_id !== azp

I think #113 probably should have just validated that `azp in trusted_audiences`
