### ISSUE TITLE
Sign in with Apple: Strategy failed with error: :enoent

### ISSUE THREAD

**Issue by alvnrapada** [pow-auth/assent#125]
So i'm trying to implement sign in with apple using pow_assent, but after signing in, it just returns an error flash `Something went wrong, and you couldn't be signed in. Please try again`

When I looked at the logs it shows:

<img width="1343" alt="Screenshot 2023-05-30 at 5 32 24 PM" src="https://github.com/pow-auth/assent/assets/62341430/b2d61ad3-5859-43ff-8d92-c9d259531f63">

Do you have any idea what causes and how to fix this? Thanks!

**Comment by danschultzer** [comment]
I realize that you may have found a solution or moved on, but the `:enoent` error means that a the private key file couldn't be read. I've made the error message more legible with #131 . Thanks for the report!
