### ISSUE TITLE
`defoverride`  for definitions from `Assent.Strategy` when `use`ing `Assent.Strategy.OAuth2.Base`

### ISSUE THREAD

**Issue by paulbalomiri** [pow-auth/assent#155]
I'm implementing a provider, which needs an aditional body parameter when calling the `token` endpoint.
in order to override `&Assent.Strategy.callback/2`, i think that the  additional `defoverridable Helpers` (or `defoverridable callback: 2`) is needed, otherwhise the implementation in my custom module is ignored.

** Should this overridable definition not be included in the `__using/2` definition of `Assent.Strategy.OAuth2.Base`?

The use definition defines these behavoiurs:

https://github.com/pow-auth/assent/blob/4457d3eb40cac19428ae45b2f00a884e93389a8b/lib/assent/strategies/oauth2/base.ex#L44-L45

The only defoverridable in the `Assent.Strategy.OAuth2.Base.__using__/1` Macro is this one:

https://github.com/pow-auth/assent/blob/4457d3eb40cac19428ae45b2f00a884e93389a8b/lib/assent/strategies/oauth2/base.ex#L58

In order to override the `callback/2` in my implementation module i need to do this:

```elixir
defmodule CanteAuth.Assent.Strategy.Anaf do
  use Assent.Strategy.OAuth2.Base
 #Shouldn't this be in Assent.Strategy.OAuth2.Base.__using__/1?
  defoverridable Helpers
 ...
  @impl Helpers
  def callback(config, params) do
```
 
Is the macro `Assent.Strategy.OAuth2.Base.__using__/1` really missing the line 
```elixir
defoverridable Helpers
```
or am I missing something obvious, for overriding functions imported from `Assent.Strategy`?

Thank you for this wonderful library! ❤️

**Comment by danschultzer** [comment]
There's no need to as you can just implement a strategy that calls `Assent.Strategy.OAuth2` directly:

```elixir
defmodule CanteAuth.Assent.Strategy.Anaf do
  @behaviour Assent.Strategy

  alias Assent.Strategy.OAuth2

  @impl Assent.Strategy
  def authorize_url(config) do
    OAuth2.authorize_url(config(config))
  end

  defp config(config) do
    # Set defaults here and merge with the config
  end

  @impl Assent.Strategy
  def callback(config, params) do
    OAuth2.callback(config(config), params)
  end

  def fetch_user(config, token), do: OAuth2.fetch_user(config, token)
end
```

This is essentially for `use Assent.Strategy.OAuth2.Base` does. We may want to allow setting something similar to the `authorization_params` for `authorize_url/2`, e.g. `grant_access_token_params`.
