### ISSUE TITLE
Incorrect @spec for authorize_url/2

### ISSUE THREAD

**Issue by diogomrts** [pow-auth/assent#158]
I noticed that the `@spec` for the `authorize_url/2` function in the Assent library is incorrect and does not match its actual return values. Specifically, the spec does not account for the `{:error, term()}` case, which causes issues with Dialyzer.

#### Current @spec

```elixir
@spec authorize_url(Keyword.t(), module()) ::
  {:ok, %{session_params: %{state: binary()}, url: binary()}}
```

#### Actual Behavior

According to the implementation, the function can return either:
- `{:ok, %{session_params: %{state: binary()}, url: binary()}}`
- `{:error, term()}`

The `@spec` should reflect this, but currently, it only defines the `{:ok, ...}` case.

#### Steps to Reproduce
1. Use the `authorize_url/2` function in a project with Dialyzer enabled.
2. Pattern match against `{:error, _}` in the function's return value.
3. Observe Dialyzer warnings indicating that the pattern `{:error, _}` can never match.

**Comment by danschultzer** [comment]
Thanks! I realized this is something that was not tested at all in the test suite, so I updated the integration server in #166 to ensure we get any typespec errors for integrations moving forward!
