### ISSUE TITLE
LinkedIn OAuth Strategy

### ISSUE THREAD

**Issue by mbuhot** [pow-auth/assent#52]
Hello and thanks for creating this great library 👍 

Is there any interest in a LinkedIn OAuth strategy, something akin to the [Ueberauth.LinkedIn](https://github.com/tableturn/ueberauth_linkedin) strategy?

**Comment by danschultzer** [comment]
Thanks, and sure, feel free to open a PR! It should be super easy 😄 

The modules a very light: https://github.com/pow-auth/assent/blob/master/lib/assent/strategies/discord.ex

For the tests I usually copy values from the documentation: https://github.com/pow-auth/assent/blob/master/test/assent/strategies/discord_test.exs
