### ISSUE TITLE
Warnings with Elixir 1.11

### ISSUE THREAD

**Issue by djthread** [pow-auth/assent#63]
During compilation, I get the warnings below repeatedly. It seems to be because [`oauther`](https://github.com/lexmag/oauther) needs to have `:crypto` and `:public_key` its `:extra_applications` config.

I raised it here: https://github.com/lexmag/oauther/pull/18

I also notice it's not seen a commit in over 2.5 years, so I thought I would bring the point up over here, as well.

Thank you, Dan, for all the hard work & sharing!

**Comment by danschultzer** [comment]
Yeah, I think I'll get rid of the oauther dependency and just build out the strategy. Always prefer as few dependencies as possible in any case 😄

**Comment by danschultzer** [comment]
Replaced oauther, and released `v0.1.18`!
