### ISSUE TITLE
OIDC normalize/2 to conform to OAuth2 normalize/2

### ISSUE THREAD

**Issue by gaiabeatrice** [pow-auth/assent#91]
I realize that the typespec for `normalize/2` belonging to the OIDC strategy is different than the one described in the docs, and the OAuth2 one, and it is making my dialyzer fail.

I believe it should be changed to 
```elixir
@callback normalize(Keyword.t(), map()) :: {:ok, map()} | {:ok, map(), map()} | {:error, term()}
```
to allow claims that don't conform to the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.1)

**Comment by danschultzer** [comment]
Good catch, thanks! Fixed in #92.

**Comment by gaiabeatrice** [comment]
@danschultzer any chance there is going to be a release soon?

**Comment by danschultzer** [comment]
New release is out, sorry for the delay!
